In [270]:
import torch
import torch.nn.functional as F
import math
import numpy as np


# (3, 2)
keys = torch.Tensor([ [1,0], #ik key
                      [0,1], #ben key
                      [-7,1]  #blij key
                    ])


# (3, 2)
values = torch.Tensor([[ 1,0], #ik value
                       [10,0], #ben value
                       [10,10] #blij value
                      ]) 

# (1, 2)
query = torch.Tensor([[-3,1]]) #ik

print(torch.matmul(query, keys.T))
qk_scaled = torch.matmul(query, keys.T) / math.sqrt(4)

print(qk_scaled )

attention = F.softmax(qk_scaled, dim=-1)
print(np.round(attention,decimals=2))

output = torch.matmul(attention, values)
output



tensor([[-3.,  1., 22.]])
tensor([[-1.5000,  0.5000, 11.0000]])
tensor([[0., 0., 1.]])


tensor([[10.0000,  9.9997]])

In [141]:
query = torch.Tensor([[1, 0]]) #ben
QK = torch.matmul(query, keys.T)
    
##scale QK by the sqrt of dk
matmul_scaled = QK / math.sqrt(4)
F.softmax(matmul_scaled, dim=-1)

softmax_output = F.softmax(matmul_scaled, dim=-1)

# Converteer de tensor naar een numpy array
softmax_numpy = softmax_output.detach().numpy()

# Rond de waardes af
rounded_values = np.round(softmax_numpy, decimals=2)
rounded_values

array([[0.38, 0.23, 0.38]], dtype=float32)

In [267]:

def scaled_dot_product_attention(Q, K, V, dk=4):
    ##matmul Q and K
    QK = torch.matmul(Q, K.T)
    
    ##scale QK by the sqrt of dk
    matmul_scaled = QK / math.sqrt(dk)
    
    attention_weights = F.softmax(matmul_scaled, dim=-1)
    print(np.round(attention_weights,decimals=2))

    ## matmul attention_weights by V
    output = torch.matmul(attention_weights, V)

    return output, attention_weights

# %%
def print_attention(Q, K, V, n_digits = 3):
    temp_out, temp_attn = scaled_dot_product_attention(Q, K, V)
    temp_out, temp_attn = temp_out.numpy(), temp_attn.numpy()
    print ('Attention weights are:')
    print (np.round(temp_attn, n_digits))
    print()
    print ('Output is:')
    print (np.around(temp_out, n_digits))

# %%
temp_k = torch.Tensor([[10,0,0],
                      [0,20,0],
                      [0,0,10],
                      [0,0,10]])  # (4, 3)

temp_v = torch.Tensor([[   1,0, 1],
                      [  10,0, 2],
                      [ 100,5, 0],
                      [1000,6, 0]])  # (4, 3)

# %%
# This `query` aligns with the second `key`,
# so the second `value` is returned.
temp_q = torch.Tensor([[0, 10, 0]])  # (1, 3)
print_attention(temp_q, temp_k, temp_v)

# %%
# This query aligns with a repeated key (third and fourth), 
# so all associated values get averaged.
temp_q = torch.Tensor([[0, 0, 10]])  # (1, 3)
print_attention(temp_q, temp_k, temp_v)

# %%
# This query aligns equally with the first and second key, 
# so their values get averaged.
temp_q = torch.Tensor([[10, 10, 0]])  # (1, 3)
print_attention(temp_q, temp_k, temp_v)

# %%
temp_q = torch.Tensor([[0, 10, 0], [0, 0, 10], [10, 10, 0]])  # (3, 3)
print_attention(temp_q, temp_k, temp_v)

tensor([[0., 1., 0., 0.]])
Attention weights are:
[[0. 1. 0. 0.]]

Output is:
[[10.  0.  2.]]
tensor([[0.0000, 0.0000, 0.5000, 0.5000]])
Attention weights are:
[[0.  0.  0.5 0.5]]

Output is:
[[550.    5.5   0. ]]
tensor([[0., 1., 0., 0.]])
Attention weights are:
[[0. 1. 0. 0.]]

Output is:
[[10.  0.  2.]]
tensor([[0.0000, 1.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.5000, 0.5000],
        [0.0000, 1.0000, 0.0000, 0.0000]])
Attention weights are:
[[0.  1.  0.  0. ]
 [0.  0.  0.5 0.5]
 [0.  1.  0.  0. ]]

Output is:
[[ 10.    0.    2. ]
 [550.    5.5   0. ]
 [ 10.    0.    2. ]]
